import {chromium} from '@playwright/test';import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'msedge',headless:true});
try{const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://localhost:3000';await page.goto(base+'/login');await page.waitForTimeout(1000);await page.screenshot({path:'outputs/login-preview.png',fullPage:true});await page.getByRole('button',{name:'Dùng tài khoản demo'}).click();await page.waitForURL('**/dashboard',{timeout:15000});await page.getByText('82% phù hợp với hồ sơ hiện tại',{exact:true}).waitFor();
for(const width of [375,768,1440]){await page.setViewportSize({width,height:900});for(const route of ['/dashboard','/profile','/map','/explore?tab=market','/ai']){await page.goto(base+route);await page.waitForTimeout(650);if(route.includes('market'))await page.locator('.geo-bubble').first().waitFor({timeout:60000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow ${width} ${route}`);if(route==='/dashboard'&&width!==768)await page.screenshot({path:`outputs/${width===375?'mobile':'desktop'}-preview.png`,fullPage:true});}}
await page.goto(base+'/explore?tab=market');await page.getByLabel('Chọn địa điểm',{exact:true}).selectOption({index:1});await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Đóng',exact:true}).click();await page.locator('.select-trigger').click();await page.getByRole('combobox',{name:'Tìm kỹ năng'}).fill('Excel');await page.getByRole('option',{name:'Excel',exact:true}).click();await page.locator('.interactive-chart').first().getByRole('button').first().focus();await page.locator('.trend-tooltip').waitFor();await page.locator('.market-map-module').screenshot({path:'outputs/geographic-map.png'});
await page.route('**/api/backend/skills/top**',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Service unavailable'})}));await page.goto(base+'/explore?tab=skills');await page.getByRole('button',{name:'Thử lại',exact:true}).waitFor();await page.unroute('**/api/backend/skills/top**');await page.getByRole('button',{name:'Thử lại',exact:true}).click();await page.locator('.skill-row').first().waitFor();
await page.route('**/api/backend/skills/top**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({skills:[]})}));await page.goto(base+'/explore?tab=skills');await page.getByText('Chưa có dữ liệu phù hợp.',{exact:true}).waitFor();await page.unroute('**/api/backend/skills/top**');
await page.goto(base+'/profile');await page.getByRole('button',{name:'Đăng xuất',exact:true}).last().click();await page.waitForURL('**/login');await page.goto(base+'/profile');await page.waitForURL('**/login');assert.deepEqual(errors,[]);console.log('PASS production UI: demo login/logout, 15 viewport/route combinations, selector, chart tooltip, geographic sheet, errors/retry/empty, route protection.');}finally{await browser.close();}

