"use client";
import { useState } from "react";
import { useProfile } from "@/components/profile-provider";
import { IntelligenceLinks } from "@/components/intelligence-links";
const categories:Record<string,string>={automation:"Có thể tự động hóa từng phần",augmentation:"AI hỗ trợ thực hiện",human:"Cần phán đoán của con người",insufficient:"Chưa đủ mô tả để đánh giá"};
type Result={tasks:{index:number;task:string;category:string;reason:string;human_review:string;future_skills:string[]}[];method:string;analyzedAt:string};
const samples={finance:["Nhập dữ liệu từ hóa đơn vào bảng tính","Đối chiếu giao dịch và chứng từ","Phân tích nguyên nhân chênh lệch doanh thu","Trao đổi với khách hàng để hiểu nhu cầu","Phê duyệt và chịu trách nhiệm báo cáo tài chính"],data:["Viết truy vấn SQL theo đặc tả đã có","Làm sạch và kiểm tra dữ liệu đầu vào","Giải thích kết quả dashboard cho người dùng","Thiết kế thí nghiệm và chọn chỉ số đánh giá","Quyết định dùng dữ liệu cá nhân trong sản phẩm"]};
export default function Transformation(){
 const {profile}=useProfile();const [tasks,setTasks]=useState(profile.tasks.join("\n")),[occupation,setOccupation]=useState(profile.target),[result,setResult]=useState<Result>(),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const [inputSource,setInputSource]=useState(profile.demo?"Nhiệm vụ từ hồ sơ demo":"Nhiệm vụ từ hồ sơ cá nhân");
 async function analyze(){setBusy(true);setError("");setResult(undefined);try{const r=await fetch("/api/transformation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({occupation,tasks:tasks.split("\n").map(t=>t.trim()).filter(Boolean)}),signal:AbortSignal.timeout(95000)});const value=await r.json();if(!r.ok)throw Error(value.error);setResult(value);}catch(e){setError(e instanceof Error?e.message:"Không thể phân tích.")}finally{setBusy(false)}}
 return <div className="stack intelligence-workspace"><section className="greeting"><span className="eyebrow">AI & TASK TRANSFORMATION ANALYSIS</span><h1>AI thay đổi công việc của bạn thế nào?</h1><p>Nhìn vào từng nhiệm vụ, giải thích phần AI có thể hỗ trợ và trách nhiệm con người.</p></section><IntelligenceLinks/><section className="card"><span className="badge">Phân tích định tính thử nghiệm</span><p>Database hiện chưa có dữ liệu task–occupation theo thời gian. Trang này phân tích nhiệm vụ bạn cung cấp; không đưa ra tỷ lệ thay thế nghề, xác suất mất việc hay xu hướng task composition đã được đo.</p><p className="source">Tham khảo cách tiếp cận theo nhiệm vụ: <a href="https://www.ilo.org/publications/generative-ai-and-jobs-2025-update" target="_blank" rel="noreferrer">ILO · Generative AI and jobs (2025)</a>. Phân loại bên dưới do Gemini đề xuất, không phải chỉ số hoặc kết luận của ILO.</p></section>
 <section className="card"><label>Nghề / bối cảnh công việc<input value={occupation} maxLength={160} disabled={busy} onChange={e=>{setOccupation(e.target.value);setResult(undefined)}}/></label><label>Nhiệm vụ — mỗi dòng một nhiệm vụ<textarea rows={7} value={tasks} disabled={busy} onChange={e=>{setTasks(e.target.value);setInputSource("Nhiệm vụ người dùng nhập");setResult(undefined)}}/></label><p className="source">{inputSource}. Tối đa 12 nhiệm vụ. Mô tả cả dữ liệu đầu vào, đầu ra và phần cần chịu trách nhiệm để có đánh giá tốt hơn.</p><div className="intel-controls"><button className="button secondary" disabled={busy} onClick={()=>{setTasks(samples.finance.join("\n"));setOccupation("Kế toán / Tài chính");setInputSource("Nhiệm vụ mẫu biên soạn — không trích từ tin tuyển dụng");setResult(undefined)}}>Dùng mẫu Tài chính</button><button className="button secondary" disabled={busy} onClick={()=>{setTasks(samples.data.join("\n"));setOccupation("IT / Data");setInputSource("Nhiệm vụ mẫu biên soạn — không trích từ tin tuyển dụng");setResult(undefined)}}>Dùng mẫu IT / Data</button><button className="button" disabled={busy||!tasks.trim()} onClick={analyze}>{busy?"Gemini đang phân tích…":"Phân tích nhiệm vụ"}</button></div>{error&&<p role="alert">{error}</p>}{busy&&<p role="status">Đang phân loại nhiệm vụ và giải thích phần cần con người kiểm tra…</p>}</section>
 {result&&<><section className="card"><h2>Bức tranh nhiệm vụ</h2><div className="metric-grid">{Object.entries(categories).map(([id,label])=><div key={id}><strong>{result.tasks.filter(t=>t.category===id).length}</strong><span>{label}</span></div>)}</div><p className="source">Đếm trong {result.tasks.length} nhiệm vụ vừa nhập. {result.method}.</p></section>{result.tasks.map(t=><section className="card task-analysis" key={t.index}><span className="badge">{categories[t.category]}</span><h2>{t.task}</h2><p>{t.reason}</p><h3>Con người cần kiểm tra gì?</h3><p>{t.human_review}</p><h3>Kỹ năng có thể cân nhắc bổ sung</h3><div className="chips">{t.future_skills.map(s=><span className="chip" key={s}>{s}</span>)}</div><p className="source">Gợi ý từ mô hình; chưa có bằng chứng tăng trưởng nhu cầu thị trường cho các kỹ năng này.</p></section>)}</>}
 </div>;
}
