"use client";
import Link from "next/link";
import { IntelligenceLinks } from "./intelligence-links";
import { useState } from "react";
import { useProfile } from "./profile-provider";
import { useResource } from "@/lib/use-resource";
import { request } from "@/lib/api";
import { cleanOccupations, cleanGrowth, coverage, priorities, transitionPath, key, type IntelligenceData, type GrowthData } from "@/lib/intelligence";
import { DataState } from "./ui";
import { GrowthRanking } from "./growth-ranking";
import { MarketPanel } from "./market-panel";
import { SearchableSelect } from "./searchable-select";
export function IntelligenceWorkspace({mode}:{mode:"organization"|"investment"|"transition"|"intelligence"}){
 const {profile,update}=useProfile();
 const [industry,setIndustry]=useState(profile.industry),[targetTitle,setTargetTitle]=useState(""),[fromTitle,setFromTitle]=useState(""),[curriculum,setCurriculum]=useState(""),[trial,setTrial]=useState<string[]>([]),[selectedSkill,setSelectedSkill]=useState("");
 const [minJobs,setMinJobs]=useState(2),[year,setYear]=useState("all");
 const data=useResource("intelligence:"+industry,s=>request<IntelligenceData>(`/intelligence/occupations?industry=${industry}`,s).then(cleanOccupations));
 const growth=useResource("priority-growth:"+industry,s=>request<GrowthData>(`/skills/growth?industry=${industry}&start=2023&end=2025`,s).then(cleanGrowth));
 const all=data.data?.occupations||[];
 const occupations=all.filter(o=>o.n_jobs>=minJobs);
 const target=occupations.find(o=>o.title===targetTitle)||occupations[0];
 const from=occupations.find(o=>o.title===fromTitle)||occupations[1]||occupations[0];
 const options=occupations.map(o=>({value:o.title,label:`${o.title} · ${o.n_jobs} tin` }));
 const ranking=priorities(occupations,growth.data?.skills||[],profile.skills,target);
 const path=from&&target?transitionPath(occupations,from.title,target.title):[];
 const alternate=path.length>2?transitionPath(occupations,from!.title,target!.title,[path[1].title]):[];
 const before=target?coverage(target,profile.skills):null,after=target?coverage(target,[...profile.skills,...trial]):null;
 const titles={organization:"Thông tin thị trường cho tổ chức",investment:"Đầu tư kỹ năng",transition:"Khám phá đường chuyển nghề",intelligence:"Khám phá nghề & kỹ năng"};
 const curriculumSkills=curriculum.split(/[,;\n]/).map(s=>s.trim()).filter(Boolean);
 const curriculumRanking=priorities(occupations,growth.data?.skills||[],curriculumSkills,target);
 const skillOptions=[...new Set(occupations.flatMap(o=>o.skills.map(s=>s.label)))].sort().map(s=>({value:s,label:s}));
 const related=selectedSkill?occupations.filter(o=>o.skills.some(s=>key(s.label)===key(selectedSkill))):[];
 function exportCurriculum(){
  const content="\uFEFF"+[["Kỹ năng còn thiếu trong danh sách nhập","Số tin trong mẫu","Số tiêu đề nghề","Ưu tiên quy tắc /100"],...curriculumRanking.map(r=>[r.skill,r.n_jobs,r.roles,r.score])].map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(",")).join("\r\n");
  const url=URL.createObjectURL(new Blob([content],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="skillmap-training-needs.csv";a.click();URL.revokeObjectURL(url);
 }
 return <div className="stack intelligence-workspace"><section className="greeting"><span className="eyebrow">SKILLMAP INTELLIGENCE</span><h1>{titles[mode]}</h1><p>Quan sát từ dữ liệu tuyển dụng · phương pháp có thể kiểm tra</p></section><IntelligenceLinks/>
 <div className="card intel-controls"><label>Ngành<select value={industry} onChange={e=>{setIndustry(e.target.value as typeof industry);setTargetTitle("");setFromTitle("");setTrial([])}}><option value="ke_toan_tai_chinh">Tài chính / Kế toán</option><option value="it_data">IT / Data</option></select></label><label>Mẫu tối thiểu mỗi tiêu đề nghề<select value={minJobs} onChange={e=>setMinJobs(Number(e.target.value))}><option value={1}>1 tin</option><option value={2}>2 tin</option><option value={5}>5 tin</option></select></label></div>
 <DataState {...data} empty={!occupations.length}>
 <section className="card"><div className="metric-grid"><div><strong>{data.data?.total_jobs}</strong><span>Tin ngành trong database</span></div><div><strong>{occupations.length}</strong><span>Tiêu đề nghề đủ điều kiện</span></div></div><p className="source">{data.data?.source}. {data.data?.method} Kỹ năng đã qua bộ lọc taxonomy; nghề không còn kỹ năng hợp lệ bị loại. Ngưỡng mẫu đang chọn áp dụng cho các phân tích nghề trên trang.</p></section>
 <section className="card"><SearchableSelect label={mode==="organization"?"Nghề đối chiếu đào tạo":"Nghề mục tiêu"} value={target?.title||""} onChange={setTargetTitle} options={options}/>{target&&<><p className="source">Nguồn: {target.n_jobs} tin có tiêu đề này. Mỗi kỹ năng đếm số tin riêng, không cộng các bí danh trùng lặp.</p><div className="chips">{target.skills.map(s=><button className="chip" key={s.label} onClick={()=>setSelectedSkill(s.label)}>{s.label} · {s.job_ids.length} tin</button>)}</div><Link className="button secondary" href="/explore?tab=jobs">Mở danh sách tin tuyển dụng</Link></>}</section>
 {mode==="intelligence"&&<><section className="card"><h2>Kỹ năng → Nghề nghiệp</h2><SearchableSelect label="Chọn kỹ năng để tìm nghề liên quan" value={selectedSkill} onChange={setSelectedSkill} options={skillOptions}/>{selectedSkill&&(!related.length?<p>Chưa có nghề đủ điều kiện.</p>:<div className="intel-list">{related.slice(0,30).map(o=><button className="intel-row" key={o.title} onClick={()=>setTargetTitle(o.title)}><span>{o.title}</span><b>{o.n_jobs} tin</b></button>)}</div>)}</section><Link className="card" href="/transformation">Nghề → nhiệm vụ → kỹ năng: mở phân tích nhiệm vụ AI</Link></>}
 {mode==="investment"&&<>
 <section className="card"><h2>Kỹ năng nên học trước</h2><p>Ưu tiên theo dữ liệu và mục tiêu; không phải ROI tài chính.</p><DataState {...growth}><div className="intel-table"><table><thead><tr><th>Kỹ năng</th><th>Điểm /100</th><th>Tin</th><th>Đổi 2023–2025</th><th>Kế hoạch</th></tr></thead><tbody>{ranking.slice(0,15).map(r=><tr key={r.skill}><td>{r.skill}{r.relevant&&<small> · có ở nghề mục tiêu</small>}</td><td>{r.score}</td><td>{r.n_jobs}</td><td>{r.change_pp===undefined?"Chưa có":`${r.change_pp>0?"+":""}${r.change_pp} đ.%`}</td><td><button className="chip" disabled={profile.plan.some(s=>key(s)===key(r.skill))} onClick={()=>update({plan:[...profile.plan,r.skill]})}>Thêm</button></td></tr>)}</tbody></table></div></DataState><details><summary>Cách tính ưu tiên</summary><p>40 điểm: số tin riêng có kỹ năng / số tin của kỹ năng phổ biến nhất trong tập đang xét. 30 điểm: có ở nghề mục tiêu. 20 điểm: thay đổi tỷ trọng dương / mức tăng lớn nhất trong ngành (2023–2025). 10 điểm: số tiêu đề nghề có kỹ năng / số tiêu đề đang xét. Chỉ xếp kỹ năng chưa có trong hồ sơ. Thiếu chuỗi thời gian: phần xu hướng bằng 0, không coi là không tăng.</p><p>Trọng số do sản phẩm chọn, chưa được kiểm định. Không có dữ liệu chi phí học, mức tăng lương hay thời lượng để tính lợi tức tài chính.</p></details></section>
 <section className="card"><h2>What-if: thêm một nhóm kỹ năng</h2><p>Chỉ mô phỏng; không sửa kỹ năng đã có trong hồ sơ.</p><div className="chips">{ranking.slice(0,15).map(r=><button className={trial.includes(r.skill)?"chip selected":"chip"} key={r.skill} aria-pressed={trial.includes(r.skill)} onClick={()=>setTrial(trial.includes(r.skill)?trial.filter(s=>s!==r.skill):[...trial,r.skill])}>{r.skill}</button>)}</div><div className="metric-grid"><div><strong>{before?.score??0}% → {after?.score??0}%</strong><span>Độ bao phủ kỹ năng có trọng số</span></div><div><strong>{before?.missing.length??0} → {after?.missing.length??0}</strong><span>Kỹ năng còn thiếu ở nghề mục tiêu</span></div></div><p>Tiêu đề nghề đạt độ bao phủ từ 50%: {occupations.filter(o=>coverage(o,profile.skills).score>=50).length} → {occupations.filter(o=>coverage(o,[...profile.skills,...trial]).score>=50).length}.</p><p className="source">Độ bao phủ = số lượt kỹ năng đã có / tổng lượt kỹ năng hợp lệ trong tin của nghề. Không đo năng lực, học vấn, kinh nghiệm hay xác suất tuyển dụng. Ngưỡng 50% chỉ dùng để so sánh mô phỏng.</p><button className="button secondary" onClick={()=>setTrial([])}>Xóa mô phỏng</button></section></>}
 {mode==="transition"&&<section className="card"><h2>Từ nghề hiện tại đến nghề mục tiêu</h2><SearchableSelect label="Nghề hiện tại" value={from?.title||""} onChange={setFromTitle} options={options}/><p className="source">Đường đi Dijkstra trên kỹ năng quan sát được. Chỉ nối hai nghề khi Jaccard ≥ 0,15. Chi phí bước = (tỷ lệ kỹ năng mới ở nghề đến)² + 0,05. Đây là độ khó theo kỹ năng, chưa tính nhiệm vụ, kinh nghiệm hoặc rào cản bằng cấp.</p>{!path.length?<div className="state">Chưa tìm được đường kết nối trong mẫu này. Thử nghề khác hoặc giảm ngưỡng mẫu.</div>:<ol className="career-pathway">{path.map((o,i)=>{const previous=i?path[i-1]:null, gap=previous?coverage(o,previous.skills.map(s=>s.label)):null;return <li key={o.title}><span className="badge">{i===0?"Xuất phát":i===path.length-1?"Mục tiêu":`Nghề trung gian ${i}`}</span><h3>{o.title}</h3><p>{o.n_jobs} tin nguồn</p>{gap&&<><p>Độ bao phủ theo kỹ năng nghề trước: {gap.score}%. Cần bổ sung {gap.missing.length} kỹ năng quan sát được.</p><div className="chips">{gap.missing.map(s=><button className="chip" key={s} disabled={profile.plan.some(p=>key(p)===key(s))} onClick={()=>update({plan:[...profile.plan,s]})}>+ {s}</button>)}</div></>}</li>})}</ol>}{alternate.length>0&&<div><h3>Đường thay thế</h3><p>{alternate.map(o=>o.title).join(" → ")}</p><p className="source">Tính lại sau khi loại nghề trung gian đầu tiên. Không khẳng định đây là tất cả đường có thể đi.</p></div>}<Link href="/investment" className="button secondary">Lập thứ tự học kỹ năng</Link></section>}
 {mode==="organization"&&<>
 <section className="card"><h2>Đối chiếu chương trình đào tạo</h2><p>Nhập kỹ năng đang dạy, mỗi dòng hoặc dấu phẩy một kỹ năng.</p><textarea rows={5} aria-label="Kỹ năng chương trình đào tạo" value={curriculum} onChange={e=>setCurriculum(e.target.value)} placeholder="Ví dụ: Excel, SQL, Power BI"/>{curriculumSkills.length>0&&target&&<><h3>Độ bao phủ nghề được chọn: {coverage(target,curriculumSkills).score}%</h3><p className="source">Đối chiếu tên kỹ năng, không đánh giá chất lượng khóa học hay năng lực sinh viên. Danh sách nhập chỉ dùng trong phiên trang này.</p><DataState {...growth}><div className="intel-list">{curriculumRanking.slice(0,10).map(r=><div className="intel-row" key={r.skill}><span>{r.skill}</span><b>{r.n_jobs} tin · ưu tiên {r.score}/100</b></div>)}</div><button className="button secondary" onClick={exportCurriculum}>Xuất nhu cầu đào tạo CSV</button><p className="source">Xếp hạng theo cùng công thức công khai tại trang Đầu tư kỹ năng; đây là phần chưa có trong danh sách bạn nhập, không phải đo skill gap của sinh viên.</p></DataState></>}</section>
 <section className="card"><h2>Nghề thay đổi theo năm</h2><label>Năm quan sát<select value={year} onChange={e=>setYear(e.target.value)}><option value="all">Tất cả các năm</option>{[...new Set(occupations.flatMap(o=>o.years.map(y=>y.year)))].sort().map(y=><option key={y}>{y}</option>)}</select></label><div className="intel-list">{occupations.map(o=>({title:o.title,count:year==="all"?o.n_jobs:o.years.find(y=>y.year===Number(year))?.n_jobs||0})).filter(o=>o.count>0).sort((a,b)=>b.count-a.count).slice(0,10).map(o=><div className="intel-row" key={o.title}><span>{o.title}</span><b>{o.count} tin</b></div>)}</div><p className="source">Đếm trong mẫu tin TopCV, không phải tổng số việc làm Việt Nam. Năm không có tin của tiêu đề này được đếm 0 trong mẫu; năm 2026 chưa đủ năm.</p></section>
 <section className="card"><h2>Nhu cầu theo kinh nghiệm</h2><div className="intel-list">{data.data?.seniority.map(r=><div className="intel-row" key={r.label||"unknown"}><span>{r.label||"Chưa xác định"}</span><b>{r.n_jobs} tin</b></div>)}</div></section>
 <section className="card"><h2>So sánh địa điểm tuyển dụng</h2><div className="intel-list">{data.data?.regions.slice(0,15).map(r=><div className="intel-row" key={r.label||"unknown"}><span>{r.label||"Chưa xác định"}</span><b>{r.n_jobs} tin</b></div>)}</div><p className="source">Nhóm theo chuỗi địa điểm gốc; một nhãn có thể gồm nhiều địa phương.</p></section></>}
 </DataState>
 {(mode==="intelligence"||mode==="organization")&&<GrowthRanking industry={industry}/>}
 {mode==="organization"&&<details className="card"><summary>Biểu đồ chuyên sâu: địa lý, xu hướng, SGI và ILOSTAT</summary><MarketPanel industry={industry} showGrowth={false}/></details>}
 </div>;
}
